spring.datasource.url=jdbc:mysql://db:3306/roles_management_db
spring.datasource.username=roles_management_db
spring.datasource.password=roles_management_db

spring.mail.username=dummyemail@gmail.com
spring.mail.password=dummypassword 



